// Generated by commsdsl2comms v3.5.0

/// @file
/// @brief Contains definition of all client input messages bundle.

#pragma once

#include <tuple>
#include "demo3/options/DefaultOptions.h"

namespace demo3
{

namespace input
{

/// @brief Messages of the protocol in ascending order.
/// @tparam TBase Base class of all the messages.
/// @tparam TOpt Protocol definition options.
template <typename TBase, typename TOpt = demo3::options::DefaultOptions>
using ClientInputMessages =
    std::tuple<
    >;

} // namespace input

} // namespace demo3


