// Generated by commsdsl2comms v3.3.0

#pragma once

#include "demo3/frame/Frame.h"
#include "cc_plugin/Message.h"
#include "cc_plugin/input/AllMessages.h"

namespace demo3
{

namespace cc_plugin
{

namespace frame
{

using Frame =
    demo3::frame::Frame<
        demo3::cc_plugin::Message,
        demo3::cc_plugin::input::AllMessages
    >;

} // namespace frame

} // namespace cc_plugin

} // namespace demo3


